BACKGROUND images/background1_950x625_197.jpg
WIDTH 950
HEIGHT 625
TITLE Simple Map

SCALE DEFAULT 0 1 255 255 255 255 255 255
SCALE DEFAULT 1 10 254 240 138 254 240 138
SCALE DEFAULT 10 25 253 224 71 253 224 71
SCALE DEFAULT 25 40 250 204 21 250 204 21
SCALE DEFAULT 40 55 234 179 8 234 179 8
SCALE DEFAULT 55 70 202 138 4 202 138 4
SCALE DEFAULT 85 100 113 63 18 113 63 18
SCALE DEFAULT 70 85 161 98 7 161 98 7

NODE node1
	LABEL Cloud Gateway
	ICON images/Cloud-Filled.svg
	POSITION 740 170

NODE node2
	LABEL Node 2
	ICON images/WorkgroupSwitch.svg
	POSITION 130 230

NODE node3
	LABEL Node 3
	ICON images/Router.svg
	POSITION 360 40

NODE node02375
	LABEL Node11
	POSITION 270 380

NODE node02590
	LABEL Node12
	POSITION 190 380

NODE node02610
	LABEL Node13
	POSITION 350 380

NODE node02724
	LABEL box
	ICON box
	INFOURL http://google.com/
	POSITION 430 380

NODE node02875
	LABEL NodeWithNote
	POSITION 740 420

LINK node1-node2
	NODES node1 node2
	BANDWIDTH 1M 1M
	WIDTH 8
	COMMENTPOS 75 25

LINK node2-node3
	NODES node2 node3
	BANDWIDTH 2M 2M
	WIDTH 8
	COMMENTPOS 75 25

LINK node02875-node2
	NODES node02875 node2
	BANDWIDTH 1M 1M
	WIDTH 8
	COMMENTPOS 75 25

