WIDTH 800
HEIGHT 600
TITLE Network Weathermap

SCALE DEFAULT 0 1 255 255 255
SCALE DEFAULT 1 10 254 240 138
SCALE DEFAULT 10 25 253 224 71
SCALE DEFAULT 25 40 250 204 21
SCALE DEFAULT 40 55 234 179 8
SCALE DEFAULT 55 70 202 138 4
SCALE DEFAULT 70 85 161 98 7
SCALE DEFAULT 85 100 113 63 18

NODE node1
	LABEL node1
	INFOURL https://172.21.21.8/
	POSITION 250 290

NODE node2
	LABEL node2
	INFOURL ssh://172.21.21.8/
	POSITION 580 250

NODE node3
	LABEL node3
	INFOURL http://google.com/
	POSITION 510 500

LINK firstlink
	NODES node1 node2
	BANDWIDTH 30M 30M
	WIDTH 7
	COMMENTPOS 83 21
	INFOURL Array

LINK secondlink
	NODES node2 node3
	BANDWIDTH 100M 100M
	WIDTH 7
	COMMENTPOS 84 26
	INFOURL Array

LINK link3
	NODES node1 node3
	BANDWIDTH 100M 100M
	WIDTH 7
	COMMENTPOS 80 26
	INFOURL Array

